// recipes/.vitepress/theme/components/IngredientsList.vue
<template>
  <h2>Ingredients</h2>
  <ul>
    <li v-for="ingredient in ingredients" :key="ingredient.name">
      {{ ingredient.name }} {{ ingredient.quantity }} {{ ingredient.unit }}
    </li>
  </ul>
</template>

<script setup>
import { useData } from 'vitepress'

const { frontmatter } = useData();
const ingredients = frontmatter.value.ingredients;
</script>

// src/components/IngredientsList.tsx
import type { Ingredient } from "@/types/recipe.js";

interface IngredientsListProps {
  readonly ingredients: readonly Ingredient[];
}

export function IngredientsList({ ingredients }: IngredientsListProps): React.ReactElement {
  return (
    <ul>
      {ingredients.map((ingredient) => (
        <li key={`${ingredient.name}-${ingredient.unit}`}>
          {ingredient.quantity} {ingredient.unit} {ingredient.name}
        </li>
      ))}
    </ul>
  );
}
