// .vitepress/theme/components/RecipeSelect.vue
<script setup>
import { computed } from "vue";
import { data as recipes } from "../recipes.data.ts";

const { selectedRecipe, customRecipeTitle, dayId } = defineProps({
  selectedRecipe: String | null,
  customRecipeTitle: String | undefined,
  dayId: String,
});

const CUSTOM_RECIPE_ID = "-1";

const emit = defineEmits(["update:recipe", "update:custom"]);

const mainRecipes = computed(() => recipes.filter((recipe) => recipe.category === "main"));

const isCustomMode = computed(() => {
  return customRecipeTitle !== undefined && customRecipeTitle !== null;
});

const handleSelectChange = (value) => {
  if (value === CUSTOM_RECIPE_ID) {
    emit("update:recipe", null);
    emit("update:custom", "");
    return;
  }

  emit("update:recipe", value);
  emit("update:custom", undefined);
};
</script>

<template>
  <div v-if="!isCustomMode">
    <select
      :id="dayId"
      :name="dayId"
      :value="selectedRecipe"
      class="w-full"
      @change="handleSelectChange($event.target.value)"
    >
      <option value="">Select a recipe</option>
      <option :value="CUSTOM_RECIPE_ID">Other (Custom)</option>
      <option v-for="recipe in mainRecipes" :value="recipe.title">
        {{ recipe.title }}
      </option>
    </select>
  </div>
  <div v-else class="custom-recipe-input">
    <input
      type="text"
      :id="dayId + '-custom'"
      :name="dayId + '-custom'"
      placeholder="Enter custom recipe name..."
      :value="customRecipeTitle"
      class="w-full"
      @input="emit('update:custom', $event.target.value)"
    />
    <button type="button" @click="emit('update:custom', undefined)" class="btn btn-alt">
      Cancel
    </button>
  </div>
</template>

<style scoped>
.custom-recipe-input {
  display: flex;
  gap: calc(var(--spacing) * 2);
  align-items: center;
}
</style>

// src/components/RecipeSelect.tsx
import { useMemo } from "react";
import type { Recipe } from "@/types/recipe.js";

const CUSTOM_RECIPE_ID = "-1";

interface RecipeSelectProps {
  readonly id: string;
  readonly recipe?: Recipe;
  readonly customRecipeTitle?: string;
  readonly recipes: readonly Recipe[];
  readonly onUpdate: (value: { recipe?: Recipe; customRecipeTitle?: string }) => void;
}

export function RecipeSelect({
  id,
  recipe,
  customRecipeTitle,
  recipes,
  onUpdate,
}: RecipeSelectProps): React.ReactElement {
  const mainRecipes = useMemo(() => recipes.filter((r) => r.category === "main"), [recipes]);

  const selectValue = customRecipeTitle !== undefined ? CUSTOM_RECIPE_ID : (recipe?.slug ?? "");

  const handleSelectChange = (event: React.ChangeEvent<HTMLSelectElement>): void => {
    const value = event.target.value;

    if (value === CUSTOM_RECIPE_ID) {
      onUpdate({ customRecipeTitle: "" });
      return;
    }

    const selected = mainRecipes.find((r) => r.slug === value);
    onUpdate({ recipe: selected });
  };

  const handleCustomTitleInput = (event: React.ChangeEvent<HTMLInputElement>): void => {
    onUpdate({ customRecipeTitle: event.target.value });
  };

  if (customRecipeTitle !== undefined) {
    return (
      <div className="custom-recipe-input w-full">
        <input
          type="text"
          id={`${id}-custom`}
          name={`${id}-custom`}
          placeholder="Enter custom recipe name..."
          value={customRecipeTitle}
          className="flex-1 min-w-0"
          onChange={handleCustomTitleInput}
        />
        <button
          type="button"
          onClick={() => onUpdate({ customRecipeTitle: undefined })}
          className="btn btn-alt"
        >
          Cancel
        </button>
      </div>
    );
  }

  return (
    <select id={id} name={id} value={selectValue} className="w-full" onChange={handleSelectChange}>
      <option value="">Select a recipe</option>
      <option value={CUSTOM_RECIPE_ID}>Other (Custom)</option>
      {mainRecipes.map((r) => (
        <option key={r.slug} value={r.slug}>
          {r.title}
        </option>
      ))}
    </select>
  );
}
