// src/components/RecipeSelect.tsx
import { useMemo } from "react";
import type { Recipe } from "@/types/recipe.js";

const CUSTOM_RECIPE_ID = "-1";

interface RecipeSelectProps {
  readonly id: string;
  readonly recipe?: Recipe;
  readonly customRecipeTitle?: string;
  readonly recipes: readonly Recipe[];
  readonly onUpdate: (value: { recipe?: Recipe; customRecipeTitle?: string }) => void;
}

export function RecipeSelect({
  id,
  recipe,
  customRecipeTitle,
  recipes,
  onUpdate,
}: RecipeSelectProps): React.ReactElement {
  const mainRecipes = useMemo(() => recipes.filter((r) => r.category === "main"), [recipes]);

  const selectValue = customRecipeTitle !== undefined ? CUSTOM_RECIPE_ID : (recipe?.title ?? "");

  const handleSelectChange = (event: React.ChangeEvent<HTMLSelectElement>): void => {
    const value = event.target.value;

    if (value === CUSTOM_RECIPE_ID) {
      onUpdate({ customRecipeTitle: "" });
      return;
    }

    const selected = mainRecipes.find((r) => r.title === value);
    onUpdate({ recipe: selected });
  };

  const handleCustomTitleInput = (event: React.ChangeEvent<HTMLInputElement>): void => {
    onUpdate({ customRecipeTitle: event.target.value });
  };

  if (customRecipeTitle !== undefined) {
    return (
      <div className="custom-recipe-input">
        <input
          type="text"
          id={`${id}-custom`}
          name={`${id}-custom`}
          placeholder="Enter custom recipe name..."
          value={customRecipeTitle}
          className="w-full"
          onChange={handleCustomTitleInput}
        />
        <button
          type="button"
          onClick={() => onUpdate({ customRecipeTitle: undefined })}
          className="btn btn-alt"
        >
          Cancel
        </button>
      </div>
    );
  }

  return (
    <select id={id} name={id} value={selectValue} className="w-full" onChange={handleSelectChange}>
      <option value="">Select a recipe</option>
      <option value={CUSTOM_RECIPE_ID}>Other (Custom)</option>
      {mainRecipes.map((r) => (
        <option key={r.title} value={r.title}>
          {r.title}
        </option>
      ))}
    </select>
  );
}

// src/components/RecipeSelect.vue
<script setup lang="ts">
import { computed } from "vue";
import { data as recipes, type Recipe } from "../recipes.data";
import type { WeekPlannerEntry } from "@/types/week-planner-entry";

const CUSTOM_RECIPE_ID = "-1";

const { id, recipe, customRecipeTitle } = defineProps<WeekPlannerEntry>();
const emit = defineEmits<{
  (e: "update", value: { recipe?: Recipe; customRecipeTitle?: string }): void;
}>();

const mainRecipes = computed(() => recipes.filter((recipe) => recipe.category === "main"));

const selectValue = computed(() => {
  if (customRecipeTitle !== undefined) return CUSTOM_RECIPE_ID;

  return recipe ? recipe.title : "";
});

const handleCustomTitleInput = (event: Event) => {
  const value = (event.target as HTMLInputElement).value;
  emit("update", { customRecipeTitle: value });
};

const handleSelectChange = (event: Event) => {
  const value = (event.target as HTMLSelectElement).value;

  if (value === CUSTOM_RECIPE_ID) {
    emit("update", { customRecipeTitle: "" });
    return;
  }

  const recipe = mainRecipes.value.find((r) => r.title === value);
  emit("update", { recipe });
};
</script>

<template>
  <div v-if="customRecipeTitle === undefined">
    <select
      :id="id"
      :name="id"
      :value="selectValue"
      class="w-full"
      @change="handleSelectChange($event)"
    >
      <option value="">Select a recipe</option>
      <option :value="CUSTOM_RECIPE_ID">Other (Custom)</option>
      <option v-for="recipe in mainRecipes" :value="recipe.title">
        {{ recipe.title }}
      </option>
    </select>
  </div>
  <div v-else class="custom-recipe-input">
    <input
      type="text"
      :id="id + '-custom'"
      :name="id + '-custom'"
      placeholder="Enter custom recipe name..."
      :value="customRecipeTitle"
      class="w-full"
      @input="handleCustomTitleInput($event)"
    />
    <button
      type="button"
      @click="emit('update', { customRecipeTitle: undefined })"
      class="btn btn-alt"
    >
      Cancel
    </button>
  </div>
</template>

<style scoped>
.custom-recipe-input {
  display: flex;
  gap: calc(var(--spacing) * 2);
  align-items: center;
}
</style>
