// .vitepress/theme/WeekPlanner.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  data as recipes,
  type Ingredient,
  type Recipe,
} from "./recipes.data.ts";
import { google } from "calendar-link";
import dayjs from "dayjs";

import RecipeSelect from "./RecipeSelect.vue";
import { Dayjs } from "dayjs";
import { CalendarIcon } from "@heroicons/vue/24/solid";

const NUMBER_OF_DAYS = 7;

interface WeekDataEntry {
  id: string;
  label: string;
  recipe: string | null;
}

const startDate = ref<Dayjs>(dayjs());

const weekData = ref<WeekDataEntry[]>([]);
const generateWeekData = () => {
  weekData.value = Array.from({ length: NUMBER_OF_DAYS }).reduce<
    WeekDataEntry[]
  >((acc, _, index) => {
    const current = startDate.value.add(index, "day");

    acc.push({
      id: current.format("YYYY-MM-DD"),
      label: current.format("dddd DD/MM/YYYY"),
      recipe: null,
    });

    return acc;
  }, []);
};
generateWeekData();

const ingredientsRequired = ref<Ingredient[] | undefined>(undefined);

const recipesByName = recipes.reduce<Record<string, Recipe>>((acc, recipe) => {
  acc[recipe.title] = recipe;
  return acc;
}, {});

const saveWeek = () => {
  const recipes = weekData.value
    .map((day) => day.recipe)
    .filter((value) => value !== null)
    .map((day) => recipesByName[day]);

  ingredientsRequired.value = recipes.reduce<Ingredient[]>((acc, recipe) => {
    recipe.ingredients.forEach((ingredient) => {
      const existing = acc.find(
        (i) => i.name === ingredient.name && i.unit === ingredient.unit,
      );
      if (existing) {
        existing.quantity += ingredient.quantity;
      } else {
        acc.push({ ...ingredient });
      }
    });

    return acc;
  }, []);
};

const getLinkToAddToGcal = (weekDataEntry: WeekDataEntry) => {
  if (!weekDataEntry.recipe) return;

  type Duration = Parameters<typeof google>[0]["duration"];

  const event = {
    title: weekDataEntry.recipe,
    start: dayjs(weekDataEntry.id).hour(19),
    duration: [1, "hour"] satisfies Duration,
    url: "https://github.com/lukasnys/cookfolio",
  };

  return google(event);
};

const onStartDateChange = (event: Event) => {
  if (!event.target) return;
  startDate.value = dayjs((event.target as HTMLInputElement).value);

  ingredientsRequired.value = undefined;
  generateWeekData();
};
</script>

<template>
  <h2>Week Planner</h2>

  <input
    type="date"
    :value="startDate.format('YYYY-MM-DD')"
    @change="onStartDateChange"
  />

  <div class="week-planner">
    <div class="week-planner__days">
      <div v-for="(day, index) in weekData" :key="day.id" class="day-field">
        <label class="day-field__label" :for="day.id">{{ day.label }}</label>
        <div class="flex justify-end flex-wrap items-center gap-2">
          <RecipeSelect
            :selectedRecipe="day.recipe"
            :dayId="day.id"
            @update:recipe="(value) => (weekData[index].recipe = value)"
            class="flex-1"
          />

          <div v-if="day.recipe" class="flex items-center gap-2">
            <IngredientsPopover
              :id="day.id"
              :recipe="recipesByName[day.recipe]"
            />

            <a
              class="btn btn-alt btn-icon"
              target="_blank"
              :href="getLinkToAddToGcal(day)"
            >
              <CalendarIcon class="size-6" />
            </a>
          </div>
        </div>
      </div>
    </div>

    <button class="btn btn-brand" @click="saveWeek">Save</button>

    <div v-if="ingredientsRequired">
      <h3>Ingredients Required</h3>
      <IngredientsList :ingredients="ingredientsRequired" />
    </div>
  </div>
</template>

<style scoped>
.week-planner {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing) * 4);
}

.week-planner__days {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing) * 2);
  background-color: var(--vp-c-bg-alt);
  padding: calc(var(--spacing) * 3) calc(var(--spacing) * 4);
  border-radius: calc(var(--spacing) * 2);
}

.day-field {
  display: flex;
  flex-direction: column;
  gap: var(--spacing);

  & .day-field__label {
    font-weight: 600;
  }
}
</style>

// src/components/WeekPlanner.tsx
import { useState, useCallback } from "react";
import dayjs from "dayjs";

import type { Recipe } from "@/types/recipe.js";
import type { WeekPlannerEntry } from "@/types/week-planner-entry.js";
import { RecipeSelect } from "./RecipeSelect.js";
import { IngredientsPopover } from "./IngredientsPopover.js";
import { WeekResult } from "./WeekResult.js";

const NUMBER_OF_DAYS = 7;

interface WeekPlannerEntryWithLabel extends WeekPlannerEntry {
  readonly label: string;
}

interface WeekPlannerProps {
  readonly recipes: readonly Recipe[];
}

function generateWeekData(startDate: dayjs.Dayjs): WeekPlannerEntryWithLabel[] {
  return Array.from({ length: NUMBER_OF_DAYS }, (_, index) => {
    const current = startDate.add(index, "day");
    return { id: current.format("YYYY-MM-DD"), label: current.format("dddd, MMM D") };
  });
}

export function WeekPlanner({ recipes }: WeekPlannerProps): React.ReactElement {
  const [startDate, setStartDate] = useState(() => dayjs());
  const [weekData, setWeekData] = useState<WeekPlannerEntryWithLabel[]>(() =>
    generateWeekData(dayjs()),
  );
  const [isResultShown, setIsResultShown] = useState(false);

  const onStartDateChange = useCallback((event: React.ChangeEvent<HTMLInputElement>): void => {
    const newDate = dayjs(event.target.value);
    setStartDate(newDate);
    setWeekData(generateWeekData(newDate));
    setIsResultShown(false);
  }, []);

  const onUpdateWeekEntry = useCallback(
    (index: number, value: { recipe?: Recipe; customRecipeTitle?: string }): void => {
      setIsResultShown(false);
      setWeekData((prev) =>
        prev.map((entry, i) =>
          i === index
            ? { ...entry, recipe: value.recipe, customRecipeTitle: value.customRecipeTitle }
            : entry,
        ),
      );
    },
    [],
  );

  return (
    <div className="week-planner">
      <input type="date" value={startDate.format("YYYY-MM-DD")} onChange={onStartDateChange} />

      <div className="week-planner__days">
        {weekData.map((day, index) => (
          <div key={day.id} className="day-field">
            <label className="day-field__label" htmlFor={day.id}>
              {day.label}
            </label>
            <div className="flex justify-end flex-wrap items-center gap-2">
              <RecipeSelect
                id={day.id}
                recipe={day.recipe}
                customRecipeTitle={day.customRecipeTitle}
                recipes={recipes}
                onUpdate={(value) => onUpdateWeekEntry(index, value)}
              />

              {day.recipe && <IngredientsPopover id={day.id} recipe={day.recipe} />}
            </div>
          </div>
        ))}
      </div>

      <button className="btn btn-brand" onClick={() => setIsResultShown(true)}>
        Save
      </button>

      {isResultShown && <WeekResult weekData={weekData} />}
    </div>
  );
}
