// src/components/WeekPlanner.tsx
import { useState, useCallback } from "react";
import dayjs from "dayjs";

import type { Recipe } from "@/types/recipe.js";
import type { WeekPlannerEntry } from "@/types/week-planner-entry.js";
import { RecipeSelect } from "./RecipeSelect.js";
import { IngredientsPopover } from "./IngredientsPopover.js";
import { WeekResult } from "./WeekResult.js";

const NUMBER_OF_DAYS = 7;

interface WeekPlannerEntryWithLabel extends WeekPlannerEntry {
  readonly label: string;
}

interface WeekPlannerProps {
  readonly recipes: readonly Recipe[];
}

function generateWeekData(startDate: dayjs.Dayjs): WeekPlannerEntryWithLabel[] {
  return Array.from({ length: NUMBER_OF_DAYS }, (_, index) => {
    const current = startDate.add(index, "day");
    return { id: current.format("YYYY-MM-DD"), label: current.format("dddd, MMM D") };
  });
}

export function WeekPlanner({ recipes }: WeekPlannerProps): React.ReactElement {
  const [startDate, setStartDate] = useState(() => dayjs());
  const [weekData, setWeekData] = useState<WeekPlannerEntryWithLabel[]>(() =>
    generateWeekData(dayjs()),
  );
  const [isResultShown, setIsResultShown] = useState(false);

  const onStartDateChange = useCallback((event: React.ChangeEvent<HTMLInputElement>): void => {
    const newDate = dayjs(event.target.value);
    setStartDate(newDate);
    setWeekData(generateWeekData(newDate));
    setIsResultShown(false);
  }, []);

  const onUpdateWeekEntry = useCallback(
    (index: number, value: { recipe?: Recipe; customRecipeTitle?: string }): void => {
      setIsResultShown(false);
      setWeekData((prev) =>
        prev.map((entry, i) =>
          i === index
            ? { ...entry, recipe: value.recipe, customRecipeTitle: value.customRecipeTitle }
            : entry,
        ),
      );
    },
    [],
  );

  return (
    <div className="week-planner">
      <input type="date" value={startDate.format("YYYY-MM-DD")} onChange={onStartDateChange} />

      <div className="week-planner__days">
        {weekData.map((day, index) => (
          <div key={day.id} className="day-field">
            <label className="day-field__label" htmlFor={day.id}>
              {day.label}
            </label>
            <div className="flex justify-end flex-wrap items-center gap-2">
              <RecipeSelect
                id={day.id}
                recipe={day.recipe}
                customRecipeTitle={day.customRecipeTitle}
                recipes={recipes}
                onUpdate={(value) => onUpdateWeekEntry(index, value)}
              />

              {day.recipe && <IngredientsPopover id={day.id} recipe={day.recipe} />}
            </div>
          </div>
        ))}
      </div>

      <button className="btn btn-brand" onClick={() => setIsResultShown(true)}>
        Save
      </button>

      {isResultShown && <WeekResult weekData={weekData} />}
    </div>
  );
}

// src/components/WeekPlanner.vue
<script setup lang="ts">
import { ref } from "vue";
import { type Recipe } from "../recipes.data";
import dayjs from "dayjs";

import RecipeSelect from "./RecipeSelect.vue";
import { Dayjs } from "dayjs";
import type { WeekPlannerEntry } from "@/types/week-planner-entry";

const NUMBER_OF_DAYS = 7;

const startDate = ref<Dayjs>(dayjs());
const weekData = ref<WeekPlannerEntryWithLabel[]>([]);
const isResultShown = ref(false);

interface WeekPlannerEntryWithLabel extends WeekPlannerEntry {
  label: string;
}

const generateWeekData = () => {
  weekData.value = Array.from({ length: NUMBER_OF_DAYS }).reduce<WeekPlannerEntryWithLabel[]>(
    (acc, _, index) => {
      const current = startDate.value.add(index, "day");

      acc.push({ id: current.format("YYYY-MM-DD"), label: current.format("dddd, MMM D") });

      return acc;
    },
    [],
  );
};
generateWeekData();

const onSaveClick = () => {
  isResultShown.value = true;
};

const onStartDateChange = (event: Event) => {
  if (!event.target) return;
  startDate.value = dayjs((event.target as HTMLInputElement).value);

  isResultShown.value = false;
  generateWeekData();
};

const onUpdateWeekEntry = (
  index: number,
  value: { recipe?: Recipe; customRecipeTitle?: string },
) => {
  isResultShown.value = false;

  const entry = weekData.value[index];
  if (!entry) return;

  entry.recipe = value.recipe;
  entry.customRecipeTitle = value.customRecipeTitle;
};
</script>

<template>
  <h2>Week Planner</h2>

  <div class="week-planner">
    <input type="date" :value="startDate.format('YYYY-MM-DD')" @change="onStartDateChange" />

    <div class="week-planner__days">
      <div v-for="(day, index) in weekData" :key="day.id" class="day-field">
        <label class="day-field__label" :for="day.id">{{ day.label }}</label>
        <div class="flex justify-end flex-wrap items-center gap-2">
          <RecipeSelect
            :id="day.id"
            :recipe="day.recipe"
            :customRecipeTitle="day.customRecipeTitle"
            @update="(value) => onUpdateWeekEntry(index, value)"
            class="flex-1"
          />

          <IngredientsPopover v-if="day.recipe" :id="day.id" :recipe="day.recipe" />
        </div>
      </div>
    </div>

    <button class="btn btn-brand" @click="onSaveClick">Save</button>

    <WeekResult v-if="isResultShown" :weekData="weekData" />
  </div>
</template>

<style scoped>
.week-planner {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing) * 4);
}

.week-planner__days {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing) * 4);
  background-color: var(--vp-c-bg-alt);
  padding: calc(var(--spacing) * 6);
  padding-top: calc(var(--spacing) * 5);
  border-radius: calc(var(--spacing) * 2);
}

.day-field {
  display: flex;
  flex-direction: column;
  gap: var(--spacing);

  & .day-field__label {
    font-weight: 600;
  }
}

.custom-recipes-reminder {
  background-color: var(--vp-custom-block-warning-bg);
  border: 1px solid var(--vp-custom-block-warning-border);
  border-radius: calc(var(--spacing) * 2);
  padding: calc(var(--spacing) * 4);

  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing) * 2);

  & p,
  ul,
  li {
    margin: 0;
  }
}
</style>
