// src/components/WeekResult.tsx
import { useMemo } from "react";
import { ArrowDownTrayIcon } from "@heroicons/react/24/solid";

import type { Ingredient, Recipe } from "@/types/recipe.js";
import { getIcsBlob } from "@/utils/calendar-events.js";
import type { WeekPlannerEntry } from "@/types/week-planner-entry.js";
import { IngredientsList } from "./IngredientsList.js";

interface WeekResultProps {
  readonly weekData: readonly WeekPlannerEntry[];
}

export function WeekResult({ weekData }: WeekResultProps): React.ReactElement {
  const downloadIcsFile = (): void => {
    const icsBlob = getIcsBlob([...weekData]);
    const url = URL.createObjectURL(icsBlob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "week-planner.ics";
    a.click();
    URL.revokeObjectURL(url);
  };

  const customRecipes = useMemo(
    () => weekData.map((day) => day.customRecipeTitle).filter((title): title is string => !!title),
    [weekData],
  );

  const ingredients = useMemo(() => {
    const recipes = weekData
      .map((day) => day.recipe)
      .filter((recipe): recipe is Recipe => !!recipe);
    const allIngredients = recipes.flatMap((recipe) => recipe.ingredients);

    return allIngredients.reduce<Ingredient[]>((acc, ingredient) => {
      const existing = acc.find((i) => i.name === ingredient.name && i.unit === ingredient.unit);
      if (existing) {
        existing.quantity += ingredient.quantity;
      } else {
        acc.push({ ...ingredient });
      }
      return acc;
    }, []);
  }, [weekData]);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between items-center gap-2">
        <h3>Ingredients Required</h3>
        <button className="btn btn-alt btn-icon" onClick={downloadIcsFile}>
          <ArrowDownTrayIcon className="size-5" />
        </button>
      </div>

      <IngredientsList ingredients={ingredients} />

      {customRecipes.length > 0 && (
        <div className="custom-recipes-reminder">
          <h4>Custom Recipes Reminder</h4>
          <p>Don&apos;t forget to add the ingredients of these recipe(s) to your shopping list:</p>
          <ul>
            {customRecipes.map((title) => (
              <li key={title}>
                <strong>{title}</strong>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// src/components/WeekResult.vue
<script setup lang="ts">
import { computed } from "vue";
import { ArrowDownTrayIcon } from "@heroicons/vue/24/solid";

import { type Ingredient, type Recipe } from "@/recipes.data";
import { getIcsBlob } from "@/utils/calendar-events";
import type { WeekPlannerEntry } from "@/types/week-planner-entry";

const { weekData } = defineProps<{
  weekData: WeekPlannerEntry[];
}>();

const downloadIcsFile = () => {
  const icsBlob = getIcsBlob(weekData);

  const url = URL.createObjectURL(icsBlob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "week-planner.ics";
  a.click();
  URL.revokeObjectURL(url);
};

const customRecipes = computed(() => {
  return weekData.map((day) => day.customRecipeTitle).filter((title): title is string => !!title);
});

const ingredients = computed(() => {
  const recipes = weekData.map((day) => day.recipe).filter((recipe): recipe is Recipe => !!recipe);
  const ingredients = recipes.flatMap((recipe) => recipe.ingredients);

  return ingredients.reduce<Ingredient[]>((acc, ingredient) => {
    const existing = acc.find((i) => i.name === ingredient.name && i.unit === ingredient.unit);
    if (existing) {
      existing.quantity += ingredient.quantity;
    } else {
      acc.push({ ...ingredient });
    }

    return acc;
  }, []);
});
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex justify-between items-center gap-2">
      <h3>Ingredients Required</h3>
      <button class="btn btn-alt btn-icon" @click="downloadIcsFile">
        <ArrowDownTrayIcon class="size-5" />
      </button>
    </div>

    <IngredientsList :ingredients="ingredients" />

    <div v-if="customRecipes && customRecipes.length > 0" class="custom-recipes-reminder">
      <h4>Custom Recipes Reminder</h4>
      <p>Don't forget to add the ingredients of these recipe(s) to your shopping list:</p>
      <ul>
        <li v-for="customRecipe in customRecipes" :key="customRecipe">
          <strong>{{ customRecipe }}</strong>
        </li>
      </ul>
    </div>
  </div>
</template>
