// src/components/IngredientsList.tsx
import type { Ingredient } from "@/types/recipe.js";

interface IngredientsListProps {
  readonly ingredients: readonly Ingredient[];
}

export function IngredientsList({ ingredients }: IngredientsListProps): React.ReactElement {
  return (
    <ul>
      {ingredients.map((ingredient) => (
        <li key={`${ingredient.name}-${ingredient.unit}`}>
          {ingredient.quantity} {ingredient.unit} {ingredient.name}
        </li>
      ))}
    </ul>
  );
}

// .vitepress/theme/components/IngredientsList.vue
<script setup lang="ts">
import type { Ingredient } from "../recipes.data";

defineProps<{ ingredients: Ingredient[] }>();
</script>

<template>
  <ul>
    <li v-for="ingredient in ingredients" :key="ingredient.name">
      {{ ingredient.quantity }} {{ ingredient.unit }} {{ ingredient.name }}
    </li>
  </ul>
</template>
